[versions]
accompanist = "0.37.3"
agp = "8.11.1"
hilt = "2.56.2"
kotlin = "2.1.20"
coroutines = "1.10.2"
ksp = "2.1.20-2.0.1"
wire = "4.9.9"

compileSdk = "36"
targetSdk = "35"
minSdk = "24"

androidx-appcompat = "1.7.1"
androidx-activity-compose = "1.10.1"
androidx-compose-bom = "2025.08.01"
androidx-hilt = "1.2.0"
androidx-lifecycle = "2.9.0"
androidx-paging = "3.3.6"
androidx-room = "2.8.2"
androidx-work = "2.11.0"
material3 = "1.4.0"
androidx-media3 = "1.8.0"
glide = "5.0.4"
glide-compose = "1.0.0-beta07"
junit = "4.13.2"
lottie = "6.6.7"
retrofit2 = "2.11.0"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-browser = { module = "androidx.browser:browser", version = "1.8.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.1.1" }

androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-material3-navsuite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3" }
androidx-compose-material-iconsCore = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version = "1.1.7" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.8.9" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx-media3" }
androidx-palette = { module = "androidx.palette:palette-ktx", version = "1.0.0" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
androidx-test-core = { module = "androidx.test:core", version = "1.6.1" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.6.1" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version = "1.2.0" }
androidx-window = { module = "androidx.window:window", version = "1.4.0" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidx-work" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version = "23.0.0" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.4.0" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.8.1" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
haze-blur = { module = "dev.chrisbanes.haze:haze", version = "1.6.9" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glide-compose" }
glide-okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
google-gson = { module = "com.google.code.gson:gson", version = "2.11.0" }
godaddy-colorpicker = { module = "com.godaddy.android.colorpicker:compose-color-picker", version = "0.7.0" }
squareup-okhttp3 = { module = "com.squareup.okhttp3:okhttp", version = "4.12.0" }
squareup-retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
squareup-retrofit2-wire = { module = "com.squareup.retrofit2:converter-wire", version.ref = "retrofit2" }
subsampling-image = { module = "com.davemorrissey.labs:subsampling-scale-image-view-androidx", version = "3.10.0" }
iielse-imageviewer = { module = "com.github.iielse:imageviewer", version = "2.1.23" }
yalantis-ucrop = { module = "com.github.yalantis:ucrop", version = "2.2.11" }

liyujiang-oadi = { module = "com.github.gzu-liyujiang:Android_CN_OAID", version = "4.2.4" }
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }

junit = { module = "junit:junit", version.ref = "junit" }

[bundles]
compose-md3 = ["androidx-compose-material3", "androidx-compose-material3-navsuite"]
paging3 = ["androidx-paging-runtime", "androidx-paging-common", "androidx-paging-compose"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
